import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { signIn, signOut, useSession } from 'next-auth/react'

export default function Home() {
  const { data: session } = useSession()

  return (
    <div className={styles.container}>
      <Head>
        <title>NextAuth | Ellipsion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          NextAuth.js <a href="#">Demo!</a>
        </h1>

        <p className={styles.description}>
          <code className={styles.code}>Next.js + NextAuth.js + MongoDB</code>
        </p>

        {!session && (
          <>
            <p className={styles.title}>
              You are not Logged In...
            </p>
            <div className={styles.grid}>
              <a onClick={signIn} href="#" className={styles.card}>
                <h2>Sign In &rarr;</h2>
                {/* <p>Find in-depth information about Next.js features and API.</p> */}
              </a>
              <a href="#" className={styles.card}>
                <h2>Sign Up &rarr;</h2>
                {/* <p>Learn about Next.js in an interactive course with quizzes!</p> */}
              </a>
            </div>
          </>
        )}

        {session && (
          <>
            {session.user.image && (
              <Image src={session.user.image} width={100} height={100} />
            )}
            <p className={styles.title}>
              You are Signed In as <a href="#">{session.user.name}</a>
              {console.log(session)}
            </p>
            <div className={styles.grid}>
              
              <a onClick={signOut} className={styles.card}>
                <h2>Sign out &rarr;</h2>
              </a>
              <a href="/secret" className={styles.card}>
                <p>Find super secret features and API.</p>
              </a>
            </div>
          </>
        )}
        {/* <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Login &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Sign Up &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
